### ISSUE TITLE
Ctrl + Click include path only works if ends with `.twig`

### ISSUE THREAD

**Issue by webrgp** [moetelo/twiggy#26] opened 2024-05-28 16:17 UTC
Ctrl + Click include path only works if ends with `.twig`. For example:

```twig
{# This will work #}
{{ include('_partials/_header.twig') }}

{# This won't #}
{{ include('_partials/_header') }}
```

Can it be more forgiving? If doesn't have extension, try finding with `.twig`, or maybe the first matching with any extension.

**Comment by webrgp** [comment] 2024-05-28 16:19
I am new to VS Code extension development, but if you point me in the direction of the code that handles that bit, I can try to fix it locally and submit a PR. I would actually prefer it, so I can get familiar with it and start to contribute more.

**Comment by moetelo** [comment] 2024-05-28 21:08
First, thank you for your interest!

For me, the definition works as expected:\
(can't take a screenshot of it so it's clear that the ctrl+click/f12 definition works, but trust me)

![image](https://github.com/moetelo/twiggy/assets/17011936/74fd6a51-08b8-459c-97d5-cfb75cee4293)

Could you provide more details into how to reproduce this behavior? My guess is that the file `_partials/_header` does not exist. Explanation below.

The definition is handled in the `DefinitionProvider` class, specifically this part:

https://github.com/moetelo/twiggy/blob/224cb3a4ff2bbe2deb269ec2ad62614a32a636dc/packages/language-server/src/definitions/index.ts#L89-L100

The `documentCache.resolveByTwigPath` method matches the templates directory so paths like `'@namespace/template.twig'` work and then checks if such file exists.

https://github.com/moetelo/twiggy/blob/224cb3a4ff2bbe2deb269ec2ad62614a32a636dc/packages/language-server/src/documents/DocumentCache.ts#L55-L56

Maybe this check is unnecessary since VS Code in this scenario shows a nice popup with a suggestion to create a new file.

----

Although the completion suggests only files with the `.twig` extension. This is looks like an issue.

![image](https://github.com/moetelo/twiggy/assets/17011936/799dc645-ad59-4543-9717-dfe381132461)

The code part that handles this:

https://github.com/moetelo/twiggy/blob/224cb3a4ff2bbe2deb269ec2ad62614a32a636dc/packages/language-server/src/completions/template-paths.ts#L60-L72

I guess we can remove the extension check [here](https://github.com/moetelo/twiggy/blob/224cb3a4ff2bbe2deb269ec2ad62614a32a636dc/packages/language-server/src/utils/getTwigFiles.ts#L18-L20) and rename this function accordingly.

**Comment by webrgp** [comment] 2024-05-28 21:24
I will check later tonight, but I should add that I noticed the issue on a Craft project, running [inside docker per your recommendation here](https://github.com/moetelo/twiggy/issues/23).

**Comment by webrgp** [comment] 2024-05-29 14:47
After reviewing your reply, I see that I didn't explain the issue correctly: ctrl+click/f12 indeed works if there is a file without extension present. At least in Craft CMS land, it searches a template on the file system in this order:

- TemplateName
- TemplateName.html
- TemplateName.twig
- TemplateName/index.html
- TemplateName/index.twig

So, on this `{{ include('_partials/_header') }}`, it would for it in order:

- _partials/_header
- _partials/_header.html
- _partials/_header.twig
- _partials/_header/index.html
- _partials/_header/index.twig

[You can find more info here](https://github.com/craftcms/cms/blob/2fa837e72a8d3eb24f8d8e1869644e2f69c794d1/src/web/View.php#L768-L841).

**Comment by moetelo** [comment] 2024-05-29 14:57
Ok, now I get it. However, this is not the case for Symfony

Could we parameterize it and provide different template resolving logic for Craft?

**Comment by webrgp** [comment] 2024-05-29 15:07
Let me think a bit on it, I am sure there is a way to thread the needle and make most usable to all cases. Can you point me to how Symfony does it?

**Comment by moetelo** [comment] 2024-05-30 07:48
I guess it's [here](https://github.com/twigphp/Twig/blob/67f29781ffafa520b0bbfbd8384674b42db04572/src/Loader/FilesystemLoader.php#L169), in the twig itself

**Comment by moetelo** [comment] 2024-05-30 08:21
To be clear: it matches the paths strictly.

As far as I understand, it works like this:

You have one root namespace, for example `symfony-project/templates`. When you type `include('something.html.twig')`, it tries to find that file in the `symfony-project/templates/something.html.twig`.

You have zero or many non-root namespaces, each with a `@`-prefixed alias. For example, when `@other` is aliased to `symfony-project/other-templates`, and you `include('@other/something.html.twig')`, it will look for the `symfony-project/other-templates/something.html.twig`.

And that's it. No magic with adding extensions to the included paths.

**Comment by webrgp** [comment] 2024-05-30 14:37
Thanks for the explanation! That means that adding the fallback won't interfere with Symphony, since strict paths are always the first choice. I will get working on a PR asap.

**Comment by moetelo** [comment] 2024-05-30 14:53
> adding the fallback won't interfere with Symphony

Yes, and that's an easy way to resolve your specific issue.

But looking further, if we would want to provide completions for template paths in this short way, without the extension, that would require adding the custom logic.

Given that [we know the type of the workspace project](https://github.com/moetelo/twiggy/blob/7a1909850e09244c28a9eb59da924bc43bfa4354/packages/vscode/package.json#L64-L73), if it's a `Craft` project or not, I'd prefer differentiating the logic for these two. Some Symfony users might be confused by seeing Twiggy resolving their path without the extension, while the Symfony app itself crashing.

----

Just trying to imagine some random scenarios :) \
Anyways, let's stick with this easy way and refactor later if needed.

**Comment by webrgp** [comment] 2024-05-30 22:10
@moetelo I've created small PR for this issue. I am still new to VSCode Extension development, so feel free to give some feedback or send me some resource links.

It took me a while to figure it out how to output the variables values. Don't get me started with trying to step debug it :joy:

**Closed** 2024-06-03 21:19 UTC
